export const APP_LOADED = "APP_LOADED",
  SET_COLOR_SCHEME = "SET_COLOR_SCHEME";

export type ActionsType = "APP_LOADED" | "SET_COLOR_SCHEME";

export const SET_PHONE_NUMBER = "SET_PHONE_NUMBER",
  SET_PIN = "SET_PIN",
  SET_OTP = "SET_OTP",
  SET_EMAIL_ADDRESS = "SET_EMAIL_ADDRESS",
  SET_PASSWORD = "SET_PASSWORD";

export type FormEnumType =
  | "SET_PHONE_NUMBER"
  | "SET_PIN"
  | "SET_PASSWORD"
  | "SET_OTP"
  | "SET_EMAIL_ADDRESS";

export const SET_USER_DETAILS = "SET_USER_DETAILS",
  SET_USER_TOKEN = "SET_USER_TOKEN",
  SET_USER_TRANSACTIONS = "SET_USER_TRANSACTIONS",
  RESET_USER_CONTEXT = "RESET_USER_CONTEXT";

export type UserType =
  | "SET_USER_DETAILS"
  | "SET_USER_TOKEN"
  | "RESET_USER_CONTEXT"
  | "SET_USER_TRANSACTIONS";

export const SET_TOAST = "SET_TOAST";

export type ToastType = "SET_TOAST";

export const SET_USER_LOCATION = "SET_USER_LOCATION";

export type NavigationType = "SET_USER_LOCATION";
